create role 'Recursos Humanos';
	grant insert, update, select on mysql.* to 'Recursos Humanos' with grant, admin option;
	grant admin to "Recursos Humanos";
	grant select, insert, update on consC.obra to 'Recursos Humanos';
	grant select, insert, update on consC.permiso to 'Recursos Humanos';
	grant select, insert, update on consC.permisoobra to 'Recursos Humanos';
	grant select, insert, update on consC.clausula to 'Recursos Humanos';
	grant select, insert, update on consC.clausulaobra to 'Recursos Humanos';
	grant select, insert, update on consC.resurtir to 'Recursos Humanos';
	grant select, insert, update on consC.renglonresurtir to 'Recursos Humanos';
	grant select, insert, update on consC.producto to 'Recursos Humanos';
	grant select, insert, update on consC.pago to 'Recursos Humanos';
	grant select, insert, update on consC.trabahadorcon to 'Recursos Humanos';
	grant select, insert, update on consC.horario to 'Recursos Humanos';
	grant select, insert, update on consC.diahora to 'Recursos Humanos';
	grant select, insert, update on consC.persona to 'Recursos Humanos'; 
	grant select, insert, update on consC.cliente to 'Recursos Humanos';
	grant select, insert, update on consC.cita to 'Recursos Humanos';
	grant select, insert, update on consC.statuscita to 'Recursos Humanos';
	grant select, insert, update on consC.colonia to 'Recursos Humanos';
	grant select, insert, update on consC.codigopostal to 'Recursos Humanos';
	grant select, insert, update on consC.ciudad to 'Recursos Humanos';
	
create role 'Chalan';
    grant select on consC.actrealizar to Chalan;
	grant select, insert on consC.horario to Chalan;
	grant select(monto_pag)	on consC.pagoact to Chalan;
	grant select, insert on consC.checador to  Chalan;
	grant select, insert on consC.horario to Chalan;
	grant select on consC.trabajadorcon to Chalan;
	grant select on consC.persona to Chalan;
	grant select on consC.direccion to Chalan;
	grant select on consC.horario to Chalan;
	grant select on consC.puedohacer to Chalan;
